# -*- coding:utf8 -*-
{
    'name': 'Modulo para Wip Confetex',
    'version': '1.0',
    'depends': [
        'project',
        'sale_management',
        'contacts',
        'stock',
        'purchase',
        'base_automation',
        'mail',
    ],
    'author': 'José Miguel López Roano',
    'category': 'Services/Project',
    'website': 'http://ctt.confetex.com',
    'summary': 'Modulo para controlar las órdenes de producción en Confetex mediante un WIP',
    'description': "",
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/conf_wip_project.xml',
        'data/conf_contacts.xml',
        'data/conf_wip_product_demo.xml',
        'data/secuencia.xml',
        'data/acciones_servidor.xml',
        'wizard/estilo_task_wizard_vw.xml',
        'wizard/espec_wizard_vw.xml',
        'report/reporte_nota_salida.xml',
        'report/reporte_desglose.xml',
        'report/reporte_pedido.xml',
        'report/reporte_tarea.xml',
        'views/project_wip_estilo_vw.xml',
        'views/project_wip_menu_vw.xml',
        'views/project_wip_especificacion_tags_vw.xml',
        'views/project_wip_especificacion.xml',
        'views/project_wip_task_vw.xml',
        'views/contact_wip_res_partner_vw.xml',
        'views/project_wip_linea_proceso.xml',
        'views/project_wip_pedido_vw.xml',
        'views/project_wip_pedido_vw.xml',
        'views/sale_wip_lista_precios_vw.xml',
        'views/project_wip_desglose_vw.xml',
        'views/stock_move_wip_vw.xml',
        'views/project_wip_nota_salida_vw.xml',
    ],
}